include:
  - board: seeeduino_xiao_ble
    shield: sheesh_left
    artifact-name: sheesh_engrammer_left
  - board: seeeduino_xiao_ble
    shield: sheesh_right
    artifact-name: sheesh_engrammer_right
