name: Build123d

on:
  # workflow_run:
  #   workflows: ["KiBot"]
  #   types:
  #     - completed
  push:
    paths:
      - '.images/edges.svg'
      - '.github/workflows/case.yml'
  pull_request:
    paths:
      - '.images/edges.svg'
      - '.github/workflows/case.yml'
  workflow_dispatch:

jobs:
  Case:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow workflow to commit to the repo
    steps:
    - uses: actions/checkout@v4
    # - uses: actions/download-artifact@v4
    #   with:
    #     name: BOARD_OUTLINE
    #     path: edges.svg
    #     run-id: ${{ github.event.workflow_run.id }}
    # - uses: actions/checkout@v4
    # - uses: INTI-CMNB/KiBot@v2_dk8
    #   with:
    #     variant: board
    #     skip: erc,drc
    #     targets: JLCPCB_POSITION
    - run: |
        echo "Installing dependencies..."
        python3 -m pip install vpype build123d
        echo "Preparing SVG"
        vpype read .images/edges.svg linemerge --tolerance 3mm linesort reloop linesimplify write .images/edges_vpype.svg
        echo "Generating case..."
        python .github/workflows/case.py
        echo "Done."
    - uses: actions/upload-artifact@v4
      with:
        name: case
        path: "case.*"


  Release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: Case
    permissions:
      contents: write  # allow workflow to commit to the rep
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: case
        run-id: ${{ github.event.workflow_run.id }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          case.step
          case.stl