name: KiBot

# Controls when the action will run.
on:
  push:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - ".github/workflows/kibot.yml"
  pull_request:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - ".github/workflows/kibot.yml"
  repository_dispatch:
    types: [run_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ERC
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          dir: Generated
          skip: drc
          targets: __NONE__
      - uses: actions/upload-artifact@v4
        with:
          name: ERC_Output
          path: Generated/*.html

  DRC:
    runs-on: ubuntu-latest
    needs: ERC
    steps:
      - uses: actions/checkout@v4
      - name: Run DRC
        uses: INTI-CMNB/KiBot@v2_dk8
        with:
          dir: Generated
          skip: erc
          targets: __NONE__
      - uses: actions/upload-artifact@v4
        with:
          name: DRC_Output
          path: Generated/*.html

  BOARD:
    runs-on: ubuntu-latest
    needs: [ERC, DRC]
    permissions:
      contents: write # allow workflow to commit to the repo
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_dk8
        with:
          dir: default
          variant: board
          skip: erc,drc
      - name: upload schematic
        uses: actions/upload-artifact@v4
        with:
          name: schematic
          path: default/schematic.svg
      - name: upload compressed gerbers and drill
        uses: actions/upload-artifact@v4
        with:
          name: pcb
          path: default/jlcpcb.zip

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write # allow workflow to commit to the repo
    needs: BOARD
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pcb
          run-id: ${{ github.event.workflow_run.id }}
      - run: ls
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "jlcpcb.zip"

  CLEAN:
    runs-on: ubuntu-latest
    needs: [ERC, DRC, BOARD]
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            DRC_Output
            ERC_Output
