name: ZMK

on:
  push:
    paths:
      - "config/**"
      # - '.github/workflows/keymap.*'
      - ".github/workflows/zmk.yml"
  pull_request:
    paths:
      - "config/**"
      # - '.github/workflows/keymap.*'
      - ".github/workflows/zmk.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: "config/build.yml"
      archive_name: "sheesh"

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write # allow workflow to commit to the repo
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sheesh
          run-id: ${{ github.event.workflow_run.id }}
      - run: ls
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: sheesh_*.uf2
